
mkdir src
mkdir src/commons
mkdir src/commons/collections

gcc -I/usr/include -I/usr/include/i386-linux-gnu -I/usr/lib/gcc/i686-linux-gnu/4.7/include -I/usr/lib/gcc/i686-linux-gnu/4.7/include-fixed -I/usr/local/include -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-commons-library/src" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-nivel-gui-library/nivel-gui" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/tad_items" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/memoria" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/commons/collections/dictionary.d" -MT"src/commons/collections/dictionary.d" -o "src/commons/collections/dictionary.o" "../src/commons/collections/dictionary.c"

gcc -I/usr/include -I/usr/include/i386-linux-gnu -I/usr/lib/gcc/i686-linux-gnu/4.7/include -I/usr/lib/gcc/i686-linux-gnu/4.7/include-fixed -I/usr/local/include -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-commons-library/src" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-nivel-gui-library/nivel-gui" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/tad_items" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/memoria" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/commons/collections/list.d" -MT"src/commons/collections/list.d" -o "src/commons/collections/list.o" "../src/commons/collections/list.c"

gcc -I/usr/include -I/usr/include/i386-linux-gnu -I/usr/lib/gcc/i686-linux-gnu/4.7/include -I/usr/lib/gcc/i686-linux-gnu/4.7/include-fixed -I/usr/local/include -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-commons-library/src" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-nivel-gui-library/nivel-gui" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/tad_items" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/memoria" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/commons/collections/queue.d" -MT"src/commons/collections/queue.d" -o "src/commons/collections/queue.o" "../src/commons/collections/queue.c"

gcc -I/usr/include -I/usr/include/i386-linux-gnu -I/usr/lib/gcc/i686-linux-gnu/4.7/include -I/usr/lib/gcc/i686-linux-gnu/4.7/include-fixed -I/usr/local/include -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-commons-library/src" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-nivel-gui-library/nivel-gui" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/tad_items" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/memoria" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/commons/bitarray.d" -MT"src/commons/bitarray.d" -o "src/commons/bitarray.o" "../src/commons/bitarray.c"

gcc -I/usr/include -I/usr/include/i386-linux-gnu -I/usr/lib/gcc/i686-linux-gnu/4.7/include -I/usr/lib/gcc/i686-linux-gnu/4.7/include-fixed -I/usr/local/include -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-commons-library/src" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-nivel-gui-library/nivel-gui" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/tad_items" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/memoria" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/commons/config.d" -MT"src/commons/config.d" -o "src/commons/config.o" "../src/commons/config.c"

gcc -I/usr/include -I/usr/include/i386-linux-gnu -I/usr/lib/gcc/i686-linux-gnu/4.7/include -I/usr/lib/gcc/i686-linux-gnu/4.7/include-fixed -I/usr/local/include -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-commons-library/src" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-nivel-gui-library/nivel-gui" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/tad_items" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/memoria" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/commons/error.d" -MT"src/commons/error.d" -o "src/commons/error.o" "../src/commons/error.c"

gcc -I/usr/include -I/usr/include/i386-linux-gnu -I/usr/lib/gcc/i686-linux-gnu/4.7/include -I/usr/lib/gcc/i686-linux-gnu/4.7/include-fixed -I/usr/local/include -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-commons-library/src" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-nivel-gui-library/nivel-gui" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/tad_items" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/memoria" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/commons/log.d" -MT"src/commons/log.d" -o "src/commons/log.o" "../src/commons/log.c"

gcc -I/usr/include -I/usr/include/i386-linux-gnu -I/usr/lib/gcc/i686-linux-gnu/4.7/include -I/usr/lib/gcc/i686-linux-gnu/4.7/include-fixed -I/usr/local/include -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-commons-library/src" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-nivel-gui-library/nivel-gui" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/tad_items" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/memoria" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/commons/process.d" -MT"src/commons/process.d" -o "src/commons/process.o" "../src/commons/process.c"

gcc -I/usr/include -I/usr/include/i386-linux-gnu -I/usr/lib/gcc/i686-linux-gnu/4.7/include -I/usr/lib/gcc/i686-linux-gnu/4.7/include-fixed -I/usr/local/include -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-commons-library/src" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-nivel-gui-library/nivel-gui" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/tad_items" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/memoria" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/commons/string.d" -MT"src/commons/string.d" -o "src/commons/string.o" "../src/commons/string.c"

gcc -I/usr/include -I/usr/include/i386-linux-gnu -I/usr/lib/gcc/i686-linux-gnu/4.7/include -I/usr/lib/gcc/i686-linux-gnu/4.7/include-fixed -I/usr/local/include -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-commons-library/src" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-nivel-gui-library/nivel-gui" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/tad_items" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/memoria" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/commons/temporal.d" -MT"src/commons/temporal.d" -o "src/commons/temporal.o" "../src/commons/temporal.c"

gcc -I/usr/include -I/usr/include/i386-linux-gnu -I/usr/lib/gcc/i686-linux-gnu/4.7/include -I/usr/lib/gcc/i686-linux-gnu/4.7/include-fixed -I/usr/local/include -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-commons-library/src" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/so-nivel-gui-library/nivel-gui" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/tad_items" -I"/home/utnso/git/tp-20131c-juanito-y-los-clonosaurios/memoria" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/commons/txt.d" -MT"src/commons/txt.d" -o "src/commons/txt.o" "../src/commons/txt.c"

gcc -shared -o "libso-commons-library.so"  ./src/commons/collections/dictionary.o ./src/commons/collections/list.o ./src/commons/collections/queue.o  ./src/commons/bitarray.o ./src/commons/config.o ./src/commons/error.o ./src/commons/log.o ./src/commons/process.o ./src/commons/string.o ./src/commons/temporal.o ./src/commons/txt.o  